### ISSUE TITLE
create new bucket ( us_weather_alerts)

### ISSUE THREAD

**Issue by MouadRS** [mberneaud/us-weather-alerts#17]

**Comment by mberneaud** [comment]
Hey @MouadRS, I created the bucket now and also gave you access to my Cloud Storage, so you can look at the bucket yourself. The name you specified was already taken, so I had to use 'us_weather_alerts_storage' instead.

**Comment by mberneaud** [comment]
If additional folders need to be created inside the bucket, let me know and I'll do it (or please do it yourself with the permissions I gave you)

**Comment by mberneaud** [comment]
I confirmed the bucket works with the new api scraper file without issue, so I closed the issue.
